tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.2/types.yaml
  - compat.yaml

inputs:

  openstack_username:
    default: { get_secret: openstack_username }

  openstack_password:
    default: { get_secret: openstack_password }

  openstack_tenant_name:
    default: { get_secret: openstack_tenant_name }

  openstack_url:
    default: { get_secret: openstack_url }

  region:
    default: { get_secret: region }

dsl_definitions:

  openstack_config: &openstack_config
    username: { get_input: openstack_username }
    password: { get_input: openstack_password }
    tenant_name: { get_input: openstack_tenant_name }
    auth_url: { get_input: openstack_url }
    region: { get_input: region }

node_templates:

  example-project:
    type: cloudify.openstack.nodes.Project
    properties:
      openstack_config: *openstack_config
      resource_id: test-project
      # Users & roles must be exist in order to assign them to this group,
      # otherwise the install workflow will fail
      users:
        - name: mohammeda
          roles:
            - test-role-1

